# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\")\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"c\n\x0cStatusReport\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x16\n\x0e\x63ommittedIndex\x18\x02 \x01(\x05\x12\x10\n\x08isLeader\x18\x03 \x01(\x08\x12\x1b\n\x03log\x18\x04 \x03(\x0b\x32\x0e.raft.LogEntry\"\x98\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"3\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"0\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06voteMe\x18\x02 \x01(\x08\"\'\n\x16GetCommittedCmdRequest\x12\r\n\x05index\x18\x01 \x01(\x05\"$\n\x14GetCommittedCmdReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\"\x12\n\x10GetStatusRequest\"4\n\x0eGetStatusReply\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.raft.StatusReport\"$\n\x11NewCommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"5\n\x0fNewCommandReply\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.raft.StatusReport2\xd4\x02\n\x04Raft\x12\x45\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x18.raft.AppendEntriesReply\x12?\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x16.raft.RequestVoteReply\x12K\n\x0fGetCommittedCmd\x12\x1c.raft.GetCommittedCmdRequest\x1a\x1a.raft.GetCommittedCmdReply\x12\x39\n\tGetStatus\x12\x16.raft.GetStatusRequest\x1a\x14.raft.GetStatusReply\x12<\n\nNewCommand\x12\x17.raft.NewCommandRequest\x1a\x15.raft.NewCommandReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGENTRY._serialized_start=20
  _LOGENTRY._serialized_end=61
  _STATUSREPORT._serialized_start=63
  _STATUSREPORT._serialized_end=162
  _APPENDENTRIESREQUEST._serialized_start=165
  _APPENDENTRIESREQUEST._serialized_end=317
  _APPENDENTRIESREPLY._serialized_start=319
  _APPENDENTRIESREPLY._serialized_end=370
  _REQUESTVOTEREQUEST._serialized_start=372
  _REQUESTVOTEREQUEST._serialized_end=470
  _REQUESTVOTEREPLY._serialized_start=472
  _REQUESTVOTEREPLY._serialized_end=520
  _GETCOMMITTEDCMDREQUEST._serialized_start=522
  _GETCOMMITTEDCMDREQUEST._serialized_end=561
  _GETCOMMITTEDCMDREPLY._serialized_start=563
  _GETCOMMITTEDCMDREPLY._serialized_end=599
  _GETSTATUSREQUEST._serialized_start=601
  _GETSTATUSREQUEST._serialized_end=619
  _GETSTATUSREPLY._serialized_start=621
  _GETSTATUSREPLY._serialized_end=673
  _NEWCOMMANDREQUEST._serialized_start=675
  _NEWCOMMANDREQUEST._serialized_end=711
  _NEWCOMMANDREPLY._serialized_start=713
  _NEWCOMMANDREPLY._serialized_end=766
  _RAFT._serialized_start=769
  _RAFT._serialized_end=1109
# @@protoc_insertion_point(module_scope)
